trigger: none

pool:
    vmImage: ubuntu-latest

steps:
    - checkout: self
      fetchTags: false
      fetchDepth: 1
      clean: true

    - task: Npm@1
      displayName: Clean install of all dependencies
      inputs:
          command: ci
          workingDir: /

    - task: Npm@1
      displayName: Run format check
      inputs:
          command: custom
          workingDir: /
          customCommand: run format:check

    - task: Npm@1
      displayName: Run lint check
      inputs:
          command: custom
          workingDir: /
          customCommand: run lint:check

    - task: Npm@1
      displayName: Run build
      inputs:
          command: custom
          workingDir: /
          customCommand: run build
